## Haruka Amami
[chara.haruka.ja]
family = "天美"
given = "春香"

[chara.haruka.ww]
family = "Amami"
given = "Haruka"

## Chihaya Kisaragi
[chara.chihaya.ja]
family = "如月"
given = "千早"

[chara.chihaya.ww]
family = "Kisaragi"
given = "Chihaya"

## Yukiho Hagiwara
[chara.yukiho.ja]
family = "萩原"
given = "雪歩"

[chara.yukiho.ww]
family = "Hagiwara"
given = "Yukiho"
