## Mirai Kasuga
[chara.mirai.ja]
family = "春日"
given = "未来"

[chara.mirai.ww]
family = "Kasuga"
given = "Mirai"

## Shizuka Mogami
[chara.shizuka.ja]
family = "最上"
given = "静香"

[chara.shizuka.ww]
family = "Mogami"
given = "Shizuka"

## Tsubasa Ibuki
[chara.tsubasa.ja]
family = "息吹"
given = "翼"

[chara.tsubasa.ww]
family = "Ibuki"
given = "Tsubasa"
